### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by acabal** [b-t-k/william-congreve_the-way-of-the-world#1]
- Missing scene CSS. Act 1 "A chocolate house" need to be styled. See the manual or Importance of Being Earnest Act 1.

- Endnotes: References need to be in a <cite> tag with the em dash inside. `— Lib.` etc

- Dedication: `<strong>` is not appropriate here because it is not strongly emphasized speech. You want `<b>` for unsemantic small caps.

- Commendatory verses: `<footer>` goes outside blockquote, it's not part of the poem

- Epilogue and Prologue: Since the entire prologue and epilogue are poems, `<blockquote>` is not necessary and you can pull the poem semantic into the parent `<section>`. Also, `chapter` is wrong here in both cases.

**Comment by b-t-k** [comment]
• The scene css is missing from the manual—I had to go back to Ernest
• Commendatory verses: ok but it  screws with the right align. I'd asked about this but I guess I asked the wrong question.
